USE easyscheduleipt;

INSERT INTO Docente (ID, Nome, Email, Password) VALUES (296, 'Abel Godinho Paulo', 'abel.paulo@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000507, 'Adolfo António da Silveira Martins', 'aasilveira@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000639, 'Adolfo Miguel Martins', 'adolfo_martins@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000178, 'Adriano Nuno Cruz Oliveira', 'adrianoncoliveira@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000140, 'Ágata Marques Fino', 'agatafino@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (176, 'Alexandra Águeda de Figueiredo', 'alexfiga@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10075, 'Alexandre José de Magalhães Figueiredo', 'alexandrevmagalhaes@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000634, 'Alexandre José Marques Pereira Sanches Florindo', 'alexandresanches@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000456, 'Alexandre Moura Antunes Luís Dias', 'alexandre-dias@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000426, 'Alexandre Pinheiro Soares', 'alexandre_soares@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (271, 'Álvaro Francisco Magalhães Teixeira', 'alvaro.teixeira@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (302, 'Amândio Francisco Caridade Silva', 'amandio.silva@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000144, 'Amaury Alexandre Seco de Seixas Pereira', 'psamaury@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000467, 'Ana Andreia Alves Garcia', 'andreiagarcia@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000265, 'Ana Carina de Oliveira Castanheiro', 'a.carina.c@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (82, 'Ana Carla Vicente Vieira', 'avieira@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000613, 'Ana Carrêlo', 'a.carrelo@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000254, 'Ana Catarina das Neves Cavaco', 'a-cavaco@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000534, 'Ana Catarina Lima Caria Pereira', 'apcaria@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000142, 'Ana Catarina Mendes Garcia', 'ana.catarina.garcia@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (3, 'Ana Cláudia Leal Marques Pires da Silva Mendes Pinto', 'claudia.silva@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000572, 'Ana Conceição', 'anaconceicao@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (83, 'Ana Cristina Barata Pires Lopes', 'anacris@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (33, 'Ana Cristina Becerra Nata dos Santos', 'anata@ipt.pt', 6);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000443, 'Ana Cristina Jacinto da Silva', 'cristinajacinto@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000559, 'Ana Filipa Vieira Lopes Joaquim', 'afilipajoaquim@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (315, 'Ana Isabel e Sousa do Carmo', 'anadocarmo@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000264, 'Ana Isabel Gaspar Pacheco', 'ana.ipacheco@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000637, 'Ana Isabel Guerra Vitorino Ferreira', 'ana.igv.ferreira@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000605, 'Ana Isabel Loureiro de Sousa Virgolino Silva', 'anaisabelvirgolino@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10047, 'Ana Luísa Junça da Silva', 'analjsilva@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000120, 'Ana Maria dos Santos Bailão', 'ana.bailao@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000213, 'Ana Maria Mendes Baldaia Marques', 'ana.marques@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10064, 'Ana Maria Rosa Lopes', 'anamrl@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (366, 'Ana Marta da Costa Sénica', 'ana.senica@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10025, 'Ana Marta Diniz Santos Rodrigues', 'ana.rodrigues@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000163, 'Ana Patrícia Bidarra dos Santos Lourenço', 'ana.bidarra@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000526, 'Ana Paula de Jesus Lopes Gaspar', 'a-gaspar@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000205, 'Ana Paula Faria Ferreira', 'anapaula.ferreira@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (187, 'Ana Paula Gerardo Machado', 'anamachado@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10063, 'Ana Paula Gomes Ribeiro', 'anapaula.ribeiro@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (353, 'Ana Raquel Vasco dos Santos Mendes', 'anamendes@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (29, 'Ana Rita de Sousa Gaspar Vieira', 'ana.vieira@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10067, 'Ana Rita do Pranto Duarte', 'ana.duarte@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000469, 'Ana Rita Vilas Boas Alves Dias', 'ana_dias@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000435, 'Ana Sofia Ramires Ferro da Costa Pessoa Sarmento de Matos', 'anasofia.costapessoa@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000139, 'Ana Sofia Torres Pereira', 'anas.pereira@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000514, 'Anabela da Cruz Pereira', 'anabela.pereira@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (84, 'Anabela Mendes Moreira', 'anamoreira@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (131, 'André Escórcio Rodrigues Soares', 'andre.escorcio@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000164, 'André Filipe Esteves Carvalho', 'afecarvalho@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (102, 'André Filipe Sá e Silva', 'andre.silva@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000545, 'André Rui Nunes Bernardes da Cunha Graça', 'andre.graca@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (100083, 'Andrea Isabel Oliveira da Costa e Sousa', 'andrea.sousa@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000424, 'Andreia Maria Alves de Almeida', 'andreia.almeida@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000382, 'Andreia Maria Meira Machado Nogueira', 'andreia-nogueira@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000594, 'Andreia Saraiva Santos', 'a.santos@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000257, 'Ângela Sofia Alves Ferraz', 'asaferraz@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000133, 'Ânia Liberato Chasqueira', 'al.chasqueira@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000420, 'Anícia Rute Rebelo Teves Conceição Trindade', 'anicia.r.trindade@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (132, 'António Anacleto Viegas Ferreira', 'antonioferreira@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (85, 'António Casimiro Teixeira Batista', 'cbatista@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000421, 'António Francisco Afonso Fraqueiro', 'antoniofraqueiro@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000575, 'António Francisco Silva Costa Marques', 'antoniofmarques@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (285, 'Antonio Gabriel Simão de Castro', 'ags_castro@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (66, 'António João de Carvalho da Cruz', 'ajcruz@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (103, 'António Jorge Martins de Araújo Gomes', 'aagomes@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1, 'António Manuel Alves Cúrdia', 'acurdia@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (86, 'António Manuel Dias Cavalheiro', 'acavalheiro@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000597, 'António Manuel Pedroso Leal', 'pedroso.leal.pl@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (164, 'António Manuel Rodrigues Manso', 'manso@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (121, 'António Martiniano Ventura', 'aventura@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000612, 'António Moreira', 'antonio-moreira@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000441, 'António Reynolds Castel-Branco', 'a-castel-branco@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000444, 'António Tibério Monte Almeida da Silva', 'a.silva@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000203, 'Aquilino Manuel Felizardo Costa', 'aquilino.felizardo@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000478, 'Ari José Marques Carvalho', 'acarvalho@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (133, 'Arlindo José Bernardo Dinis', 'arlindodinis@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000547, 'Brígida Alexandra Brás Lopes', 'bablopes@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000393, 'Bruna Isabel Batista do Nascimento', 'brunanascimento@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000375, 'Bruno Alberto Nunes Coelho', 'bruno.coelho@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000431, 'Bruno Alexandre Martins Raposo', 'b.raposo@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000404, 'Bruno Filipe Nunes Farinha Nascimento Melo', 'bnascimentomelo@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (100085, 'Bruno Manuel de Almeida Santos', 'bruno.almeidasantos@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (134, 'Bruno Miguel da Silva Valada', 'brunovalada@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (106, 'Bruno Miguel Santana Chaparro', 'bruno.chaparro@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000522, 'Bruno Rosa Marques Luís', 'bmluis@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (23, 'Carina Frias de Oliveira', 'carinafoliveira@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (9, 'Carla Alexandra de Castro Carvalho e Silva', 'carlasilva@ipt.pt', 6);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000125, 'Carla Dias Marques da Cruz', 'carlamcruz@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (135, 'Carla Maria Freitas dos Santos Joaquim', 'carla.joaquim@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (67, 'Carla Maria P. Calado Rodrigues do Rego', 'cmrego@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (24, 'Carla Sofia Catarino Silva', 'sofia.csilva@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000394, 'Carla Sofia Costa Pott Larsen', 'csofialarsen@ipt.pt', 6);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000476, 'Carla Susete Gonçalves Francisco', 'carlasusete@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000554, 'Carlos Alberto de Amaral Ribeiro', 'c.amaral.ribeiro@ipt.pt', 6);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (88, 'Carlos Alberto Farinha Ferreira', 'cferreira@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000625, 'Carlos Alberto Moisés Bento', 'carlos-bento@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (107, 'Carlos Alexandre Campos Pais Coelho', 'cccampos@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000389, 'Carlos André Araújo Salgado', 'andre.salgado@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (150, 'Carlos David Magalhães Queiroz', 'carloqrz@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (137, 'Carlos Fernando Calhau Trigacheiro', 'carlostrigacheiro@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (17, 'Carlos Filipe Perquilhas Baptista', 'carlos.perquilhas@ipt.pt', 6);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (89, 'Carlos Jorge Trindade da Silva Rente', 'c.rente@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (152, 'Carlos José Rodarte de Almeida Veloso', 'cveloso@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000141, 'Carlos Manuel Costa da Silva', 'carlosmcs@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10036, 'Carlos Manuel Dias Filipe', 'carlosmanuelfilipe@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000385, 'Carlos Manuel Gaspar Touret', 'carlostouret@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (325, 'Carlos Manuel Martins Costa', '', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000306, 'Carlos Miguel da Fonseca Gama', 'migueldafonsecagama@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000621, 'Carlos Silva', 'csilva@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000616, 'Carlos Silvério', 'carlossilverio@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000611, 'Carmen Zita Batalha Garcia Monereo', 'carmen.g.monereo@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000570, 'Catarina Hilario', 'catarina-hilario@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10026, 'Catarina Isabel de Assunção Grilo', 'catarinagrilo@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000608, 'Catarina Margarida Duarte Belo Calado Brito', 'catarina.margarida.b@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000560, 'Cátia Filipa dos Reis Maneca', 'catia_maneca@ipt.pt', 6);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000553, 'Cecília Alexandra Oliveira do Amaral', 'cecilia.amaral@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (188, 'Cecília de Melo Correia Baptista', 'cecilia@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10070, 'Célia Maria Felizardo Meira', 'celia.meira@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (165, 'Célia Maria Nunes Barreto', 'celiabarreto@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000541, 'Célia Maria Ramos Serra Reis Barroso', 'celia.reis@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (34, 'Célio Gonçalo Cardoso Marques', 'celiomarques@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000508, 'Cesário Garcia Mil-Homens', 'cesario@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (318, 'Charly Rosa da Silva', 'charlysilva@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10050, 'Christopher John Harold Pratt', 'christopher.pratt@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000489, 'Cláudia Cristina Celina Braga', 'cbraga@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (295, 'Cláudia Liliana Sousa Rosa Henriques', 'claudia.rosa@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10071, 'Cláudia Sofia Carrilho Morgado', 'claudia.morgado@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (100095, 'Cláudia Sofia Charneca Gouveia', 'claudiasofiagouveia@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000475, 'Cláudia Sofia Passão Paixão', 'claudia.s.paixao@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000638, 'Cláudio Inácio Monteiro', 'cmonteiro@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000402, 'Cleon Adonis Gonçalves Fialho dos Santos', 'cleon@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000580, 'Cristiana Mercê', 'cristianamerce@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (90, 'Cristina Margarida Rodrigues Costa', 'c.costa@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000629, 'Cristina Maria Ferreira Cachado', 'cristina.cachado@ipt.pt', 6);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (186, 'Cristina Maria Mendes Andrade', 'c.andrade@ipt.pt', 6);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000392, 'Cristina Maria Rebouta de Sousa Robalo', 'cristinasrobalo@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000586, 'Cristina Paula Lopes Ferreira de Sousa Marques', 'cristinasmarques@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (139, 'Daniel Ferreira de Oliveira', 'danieloliveira@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000635, 'Daniel Nunes da Silva', 'daniel_n_silva@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000472, 'David Miguel Martins Sousa', 'd.sousa@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000351, 'Diana da Silva Dias', 'dianadias@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000622, 'Diana Torres', 'diana.torres@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10048, 'Dina Maria Barreira Ramos', 'dinaramos@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (189, 'Dina Maria Ribeiro Mateus', 'dinamateus@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (100090, 'Dina Teresa Ferreira Lopes', 'dina.lopes@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000276, 'Diogo dos Santos Mendes', 'diogo.santos.mendes@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000204, 'Diogo Filipe Costa Pimenta', 'diogopimenta@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (100088, 'Diogo Gomes Almeida Chambel Lopes', 'diogochambellopes@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000248, 'Diogo Miguel Alcaçarenho Rosa', 'diogo.rosa@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (122, 'Duarte Pinto Coelho Amaral Netto', 'duarte.netto@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (383, 'Edgar Ferreira Enes', 'edgar.enes@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000479, 'Eduardo António da Costa Dias Ribeiro', 'ediasribeiro@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (301, 'Eduardo Fontão MontAlverne Brou', 'ebrou@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000523, 'Eduardo Jorge Jesus Soares', 'eduardosoares@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (255, 'Eduardo Jorge Marques de Oliveira Ferraz', 'ejmoferraz@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (48, 'Eduardo Manuel da Silva S. Pinhão', 'pinhao.eduardo@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000537, 'Eleonora Beatriz dos Santos Melo da Silva', 'eleonora.b.s.m.s@ipt.pt', 6);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000179, 'Élia Patrícia Rato Calvo', 'eliaprcalvo@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000122, 'Elisabete de Jesus Rosado Rolo', 'elisabeterolo@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10061, 'Elisabete Lopes Mendes Gonçalves', 'elisabete.goncalves@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000188, 'Emanuela Sara Hanson Fragoso', 'emanuelafragoso@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (49, 'Emídio Jorge Buchinho de Oliveira', 'emidio_buchinho@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10027, 'Éricka Maria Costa de Amorim', 'ericka.amorim@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (685, 'Eugenia Cunha', '', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (546, 'Eugénio Manuel Carvalho Pina de Almeida', 'epalmeida@ipt.pt', 6);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10, 'Eugénio Manuel Carvalho Pina de Almeida', 'epalmeida@ipt.pt', 6);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (153, 'Eunice Ferreira Ramos Lopes', 'eunicelopes@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000556, 'Fábio Miguel Lopes Ferreira', 'fabio.ferreira@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000563, 'Fátima Alexandra Marques Andrade Rodrigues', 'f.rodrigues@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (194, 'Fátima Edite Pires Pereira Casado', 'f.casado@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000480, 'Fernanda Catarina Amaro Cavalheiro', 'fernanda.cavalheiro@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000373, 'Fernanda Maria de Almeida Santos Mendes', 'fernanda-mendes@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10028, 'Fernanda Maria de Oliveira Santos', '', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000558, 'Fernanda Maria Pacheco Freire Marques da Conceição', 'f_conceicao@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (68, 'Fernando Augusto Desterro Oudinot Larcher Nunes', 'larcher@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10044, 'Fernando Augusto Rodrigues Coimbra', 'f-coimbra@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000517, 'Fernando da Conceição Batista', 'fernando.batista@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (91, 'Fernando Dias Martins', 'fdmartins@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (69, 'Fernando dos Santos Antunes', 'fantunes@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000403, 'Fernando Jorge Lima dos Santos Barros', 'fjlbarros@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000501, 'Fernando José Simões Gonçalves', 'fernando.goncalves@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (70, 'Fernando Manuel Conceição Costa', 'fmccosta@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (166, 'Fernando Manuel Craveiro Coelho', 'fernando.coelho@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (92, 'Fernando Manuel Lino Gonçalves Antunes', 'flantunes@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (71, 'Fernando Sanchez Salvador', 'fssalvador@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (169, 'Fernando Sérgio Hortas Rodrigues', 'sergio.rodrigues@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000473, 'Filipa Cristiana Reis de Oliveira', 'f-oliveira@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10065, 'Filipa Raposo do Amaral Ribeiro do Rosário', 'filipadorosario@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000413, 'Filipa Vieira Spínola', 'fvspinola@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000628, 'Filipe Alexandre Pereira Luís', 'filipeapluis@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10037, 'Filipe José Martins Carracinha', 'filipe.carracinha@renova.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000407, 'Filipe Manuel Martins Raminhos', 'framinhos@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000562, 'Filomena Maria Matias Ferreira', 'fferreira@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (108, 'Flávio Rodrigues Fernandes Chaves', 'flaviochaves@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000527, 'Francisco de Bivar Velho da Costa Campos', 'franciscocampos@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000516, 'Francisco Godinho Barbosa', 'francisco@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000599, 'Francisco Gonçalves Baptista de Campos', 'camposfrancisco@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (93, 'Francisco José Alexandre Nunes', 'fnunes@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000557, 'Francisco Luís Ferreira Bento', 'franciscobento@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (35, 'Francisco Paulo Vilhena Antunes Bernardino Carvalho', 'fpcarvalho@ipt.pt', 6);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000576, 'Frederico Casimiro', 'frederico.casimiro@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (94, 'Gabriel Pereira Pires', 'gppires@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000129, 'Gabriel Santos Carvalhal Evangelista', 'gabriel.evangelista@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (418, 'George Harold Nash', 'george.nash@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (343, 'Georgino da Conceição Gonçalves Serra', 'georgino.serra@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000486, 'Gisela Maria Graça de Oliveira', 'giselamoliveira@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000278, 'Gonçalo André Moço Falcão', 'goncalofalcao@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (177, 'Gonçalo Cardoso Leite Velho', 'gonvelho@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000619, 'Gonçalo Carvalho', 'goncalocarvalho@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (100094, 'Gonçalo Nuno Rodrigues Brás', 'goncalo.bras@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (51, 'Hália Filipa da Costa Santos', 'halia.santos@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (170, 'Hélder da Corte Pestana', 'helder.pestana@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000383, 'Helder Filipe Marques Pereira Gonçalves', 'helder-goncalves@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (72, 'Helena Cláudia Telo Falcão Neto', 'cfalcao@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (100081, 'Helena Ferreira Pinto Pinheiro de Melo Dias dos Santos', 'helena.santos@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (323, 'Helena Margarida da Cunha Carrilho Serrano', 'helenaserrano@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (18, 'Helena Pereira Marques Mendes Grilo', 'helenagrilo@ipt.pt', 6);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (180, 'Henrique Carlos dos Santos Mora', 'carlos.mora@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (98, 'Henrique Joaquim de Oliveira Pinho', 'hpinho@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (11, 'Hermínia Maria Pimenta Ferreira Sol', 'hsol@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000502, 'Hermínio Marques Henrique', 'herminiohenrique@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (421, 'Hipólito Collado Giraldo', 'hipolitocollado@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10072, 'Horácio Hugo Ferreira Faria de Azevedo e Silva', 'hugo.silva@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000121, 'Hugo Filipe Mendes Magalhães', 'hugo.magalhaes@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000488, 'Hugo Filipe Teixeira Gomes', 'h-gomes@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000436, 'Inaê Pimentel Santa Ana', 'inaeana@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000477, 'Inês de Jesus Gaspar Cardoso Araújo', 'inesaraujo.lied@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000598, 'Inês de Jesus Henriques Costa', 'ineshenriquescosta@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (7, 'Inês Domingues Serrano', 'inesserrano@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000631, 'Inês Mascarenhas do Vale', 'ines.mvale@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (125, 'Inês Pereira de Almeida de Bettencourt da Câmara', 'icamara@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000387, 'Inês Roque da Costa', 'inescosta@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000428, 'Isabel Lucília Lopes dos Santos Martins', 'imartins@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (200, 'Isabel Maria da Cruz Ferreira', 'iferreira@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000653, 'Isabel Maria da Silva Rodrigues Pinto dos Reis', 'isabelpintodosreis@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (190, 'Isabel Maria Duarte Pinheiro Nogueira', 'inogueira@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000521, 'Jacinto Luis Azevedo Carvalho', 'jlacarvalho@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (305, 'Joana Conceição dos Santos', 'joana.santos@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000445, 'Joana Leiria Cabral Ferreira', 'joana.cabralferreira@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10057, 'Joana Margarida Gaspar Carvalho', 'joana.carvalho@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000384, 'João Alexandre Correia Gomes', 'j.correia.gomes@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000422, 'João André Rozendo Nasi Pereira', 'joao@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000124, 'João Carlos Lopes Ferreira', 'joaoferreira@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (30, 'João Diogo Seiça Pereira Seguro', 'joaoseguro@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10066, 'João Ferreira Botas', 'joaobotas@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000513, 'João Filipe Rodrigues Silva', 'j_silva@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000620, 'João Freitas Pinto', 'jfreitaspinto@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (74, 'João Luís Farinha Antunes', 'jlfa@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (167, 'João Manuel de Sousa Nunes Costa Rosa', 'costarosa@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (31, 'João Manuel Mourão Patrício', 'jpatricio@ipt.pt', 6);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000209, 'João Manuel Pinheiro de Almeida', 'joaompalmeida@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000372, 'João Miguel de Oliveira Pitacas', 'joao.pitacas@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000255, 'João Miguel Magalhães Fernandes Cordeiro', 'jcordeiro@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000313, 'João Paulo Mateus Pedro', 'j-pedro.techart@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (75, 'João Paulo Pereira de Freitas Coroado', 'jcoroado@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000579, 'João Paulo Reis Gonçalves Moreira de Brito', 'jbrito@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000418, 'João Paulo Schaller Dias Gonçalves', 'joao.schaller@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (111, 'João Paulo Tomás Henriques', 'j.henriques@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000609, 'João Pedro Amaral Balina', 'joaobalina@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000136, 'João Pedro Carvalho Dias', 'joaopdias@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10022, 'Joâo Pedro de Matos Dâmaso', 'jpdamaso@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000345, 'João Pedro Dias Fontes da Costa', 'j_costa@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000470, 'João Pedro Fernandez Bonniz', 'joao_bonniz@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (342, 'João Pedro Freire Fonseca da Luz', 'joaopluz@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000207, 'João Pedro Tomaz Simões', 'jpsimoes@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (53, 'João Ricardo Mendes de Freitas Pereira', 'joaopereira@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000618, 'João Simões', 'joaosimoes@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000504, 'João Telmo Simões dos Santos Reis', 'joao-reis@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10038, 'João Tiago Lopes Garcia', '', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000529, 'Joaquim Luís Rodrigues Bonixe', 'bonixeluis@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000275, 'Joaquim Manuel Ruivo de Oliveira Serrano', 'joaquim.m.serrano@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (100086, 'Joel Alexandre da Silva de Jesus', 'joel.jesus@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (196, 'Jorge Adelino da Cunha Ribeiro Pires', 'jorgeadelino@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000135, 'Jorge Humberto dos Santos Seabra', 'jorge.seabra@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (112, 'Jorge Manuel Afonso Antunes', 'jorge.antunes@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (95, 'Jorge Manuel Correia Guilherme', 'jorge.guilherme@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000591, 'Jorge Manuel da Silva Valente', 'jorge-valente@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (141, 'Jorge Manuel Marques Simões', 'jorgesimoes@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10034, 'Jorge Miguel Oliveira Lourenco Ferreira', 'jorgemiguelferreira@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (8, 'Jorge Morarji dos Remédios Dias Mascarenhas', 'jmascarenhas@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000518, 'Jorge Rafael Nogueira Raposo', 'jorge.raposo@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000406, 'José Alberto de Figueiredo Oliveira Rodrigues', 'jose_rodrigues@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000371, 'José António Ferreira dos Santos', 'jferreira@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (100089, 'José António Marques de Oliveira e Vieira da Cunha', 'j.antonio.cunha@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (36, 'José António Ribeiro Mendes', 'jmendes@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000409, 'José Carlos de Sousa Rodrigues de Almeida', 'j_almeida@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (151, 'José Casimiro Nunes Pereira', 'casimiro@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (97, 'José Filipe Correia Fernandes', 'josefern@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10058, 'José Filipe Moreira da Costa', 'jose.costa@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000200, 'José Francisco Taborda Curate', 'fcurate@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (123, 'José Joaquim de Jesus Soudo', 'josesoudo@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000374, 'José Júlio Firmino das Neves', 'jjneves@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (124, 'José Luis A. Bobela Bastos Carreiras', 'jcarreiras@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000430, 'José Luís Ferreira Silva', 'j.silva@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (100098, 'José Luís Sousa Soares de Oliveira Braga', 'jlbraga@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000350, 'José Manuel Albuquerque Martins', 'j-martins@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (142, 'José Manuel Barros Pinheiro Nogueira', 'nogueira@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (37, 'José Manuel Borges Henriques Faria Paixão', 'jfpaixao@ipt.pt', 6);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (143, 'José Manuel Lopes Farinha', 'josefarinha@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (168, 'José Manuel Palma Redes Ramos', 'jpramos@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (101, 'José Manuel Quelhas Antunes', 'jmantunes@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (259, 'José Miguel Ferreira Graça', 'miguel.graca@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000544, 'José Paulo da Costa Rêgo', 'jpcrego@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000427, 'José Pedro Franco Rodrigues', 'j-rodrigues@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000138, 'José Vasco Gaio Monteiro Barroco Carvalho', 'jvcarvalho@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (171, 'Júlio César Moita Jorge Ruivo da Silva', 'jsilva@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000395, 'Laura Maria Marques Machado de Carvalho', 'laurammmcarvalho@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (77, 'Leonor da Costa Pereira Loureiro', 'leonorloureiro@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000134, 'Lígia Salgueiro Coutinho Mateus', 'ligia.mateus@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000304, 'Liliana Cristina Vidais Rosa', 'lcvrosa@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000615, 'Liliana Ramos', 'lilianaramos@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000481, 'Lionel Martins Louro', 'lionellouro@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (223, 'Luis Agnelo de Almeida', 'laa@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000123, 'Luís Alberto de Jesus Gaio Curvelo', 'luis.curvelo@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (56, 'Luis Alexandre de Jesus Falcão', 'luisjesusfalcao@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (195, 'Luís António Antunes Francisco', 'luisfrancisco@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000193, 'Luís António Rodrigues de Figueiredo Ferreira Pereira', 'luis.pereira@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000561, 'Luís Carlos Duarte dos Reis', 'luis.duarte.reis@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (128, 'Luís Carlos Martins Cardoso', 'luiscardoso@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (274, 'Luis Filipe Cunha Moreira', 'luismoreira@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (100092, 'Luís Filipe do Carmo Crispim Ribeiro', 'filipecrispim@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (275, 'Luis Filipe Neves Carreira dos Santos', 'lsantos@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000289, 'Luís Filipe Raposo Pereira', 'fpereira@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (234, 'Luis Filipe Rocha de Almeida', 'lfalmeida@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (100097, 'Luís Filipe Rui Oliveira Caetano', 'luiscaetano@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000415, 'Luís Francisco Marques da Costa Gaspar', 'luis.f.gaspar@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000577, 'Luís Gonzaga', 'lgonzaga@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000411, 'Luís José Canteiro', 'lcanteiro@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000512, 'Luís Manuel do Espírito Santo Ramos', 'lr.luisramos@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (155, 'Luís Manuel Mota dos Santos Figueira', 'lmota@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (269, 'Luís Miguel Alves de Oliveira', 'luis_o@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10052, 'Luís Miguel Cardoso Vilhena Pereira da Silva', '', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000376, 'Luís Miguel de Oliveira da Silva', 'miguel.silva@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000453, 'Luís Miguel Ferreira de Oliveira', 'luisoliveira.miguel@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (57, 'Luís Miguel Ferreira Nunes', 'luismfnunes@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10069, 'Luís Miguel Geadas Grades', 'luis.grades@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (235, 'Luis Miguel Lindinho da Cunha Mendes Grilo', 'lgrilo@ipt.pt', 6);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (276, 'Luís Miguel Lopes de Oliveira', 'loliveira@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (113, 'Luís Miguel Marques Ferreira', 'luismmferreira@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (208, 'Luís Miguel Merca Fernandes', 'luism@ipt.pt', 6);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (267, 'Luis Miguel Segurado Pavão Martins', 'luispavao@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (58, 'Luís Pires Correia', 'luis.correira@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000180, 'Luísa Maria da Silva Gonçalves', 'luisa.goncalves@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (268, 'Luiz Miguel Oosterbeek', 'loost@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (224, 'Manuel Alberto Nogueira Henriques Rosa', 'manuel.rosa@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000596, 'Manuel António Anjos Neto de Azevedo', 'm.azevedo@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10029, 'Manuel António Diogo Carlos', 'manuel.carlos@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (231, 'Manuel Fernando Martins de Barros', 'fmbarros@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (423, 'Manuel José Ribeiro Pacheco e Silva', 'manuelpacheco@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000515, 'Manuela Maria Soares Pontes', 'manuela.maria.pontes@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (100079, 'Manuela Sofia da Conceição Silva', 'manuelasofia.silva@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (211, 'Marco António Mourão Cartaxo', 'mamcartaxo@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000617, 'Marco Batista', 'marcobatista@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000568, 'Marco Branco', 'marcobranco@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000137, 'Marco Filipe de Almeida Santos Oliveira', 'marcofoliveira@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10051, 'Marco Paulo Pereira Silva', '', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000118, 'Margarida Cristina Freire Simões Moleiro', 'margaridamoleiro@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000202, 'Margarida Sofia de Freitas Oliveira', 'margarida.foliveira@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (156, 'Maria Alexandra Falcão Bento Baptista Vilhena de Carvalho', 'a.carvalho@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10030, 'Maria Ángeles Corzo Troncoso', '', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (230, 'Maria Cristina Oliveira da Costa', 'ccosta@ipt.pt', 6);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (59, 'Maria da Conceição Correia Salvado Pinto Pereira Barras Romana', 'maria.romana@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (146, 'Maria da Conceição de Jesus Fortunato', 'conceicao.fortunato@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000549, 'Maria da Conceição Rodrigues Teixeira Martins', 'm_martins@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (100082, 'Maria de Fátima Matos Navalho Silva Peixoto', 'mfatima.peixoto@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10031, 'Maria de Fátima Nunes Simões Duro', 'mfatimaduro@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (147, 'Maria de Fátima Rodrigues Pedro', 'fatimapedro@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (233, 'Maria de Lurdes Belgas da Costa Reis', 'lbelgas@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (148, 'Maria do Rosário Mendes Godinho Passos Baeta Neves', 'mrosariobneves@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (158, 'Maria Fernanda Pires Aparício', 'fa@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000258, 'Maria Filipa Ferreira da Silva Pias', 'filipa.pias@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (159, 'Maria Graciete da Purificação Reis Henriques Honrado', 'graciete.honrado@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (40, 'Maria Helena Morgado Monteiro', 'helena.monteiro@ipt.pt', 6);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000455, 'Maria Inês Marques Serralheiro Nabais', 'ines.serralheiro@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000214, 'Maria Isabel Leandro Pinheiro de Almeida Tissot Daguette', 'isabeltissot@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (41, 'Maria Isabel Vaz Pitacas', 'ipitacas@ipt.pt', 6);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (277, 'Maria João Bom Mendes dos Santos', 'mariajoaobom@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000511, 'Maria João Cabrita Matias Ramos Bugarin', 'mjramosbugarin@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000119, 'Maria João Cassis Valadas Revez', 'mjoaorevez@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (25, 'Maria João da Costa Antunes Inácio', 'mjantunes@ipt.pt', 6);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000532, 'Maria João Gomes Pires', 'mariajoao.g.pires@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (417, 'Maria José Brito Alves Martinho', 'mjmartinho@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (237, 'Maria Madalena Giraldes Barba Pessoa Jorge Oudinot Larcher', 'mlarcher@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (225, 'Maria Manuela Morgado Fernandes Oliveira', 'mfernandes@ipt.pt', 6);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000482, 'Maria Paula Pinto Soares', 'maria-soares@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000263, 'Maria Rita de Oliveira Nunes d''Angelis', 'mnunesd@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (278, 'Maria Teresa da Luz Silveira', 'tersilveira@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000277, 'Maria Teresa Florentino', 'mariaflorentino@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (256, 'Maria Teresa Ribeiro Pereira Desterro', 'teresa.desterro@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000493, 'Mário Durão', 'mariodurao@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000565, 'Mario Ferreira', 'mario_ferreira@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (236, 'Mário Helder Rodrigues Gomes', 'mgomes@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000542, 'Mário José Filipe Gomes', 'mariofgomes@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (313, 'Mário Miguel Jesus Carvalho', 'mario.carvalho@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000449, 'Mário Ricardo Lopes da Silva', 'm.silva@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000369, 'Mário Ricardo Silveiro de Barros', 'msbarros@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000505, 'Mário Rui Betes Rodrigues Lopes', 'mrbetes@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000533, 'Marisa Mendes Fernandes Ribeiro Kulyk', 'mkulyk@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (26, 'Marta Margarida Santos Dionísio', 'marta.dionisio@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (216, 'Marta Sicurella', 'marta.sicurella@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000251, 'Marta Veiga da Silva Mira Nalha', 'martanalha@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000566, 'Mauro Miguel', 'mauromiguel@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (100101, 'Micael Santos Couceiro', 'micaelcouceiro@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (218, 'Miguel Alexandre Pereira Sanches', 'msanches@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000540, 'Miguel Ângelo Semedo Folgado', 'folgado.mas@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000388, 'Miguel António Lopes Barbosa', 'miguelantoniobarbosa@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000370, 'Miguel Carrasqueira Salvador Baptista', 'miguel_baptista@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (257, 'Miguel de Barros Serra Cabral de Moncada', 'miguel.moncada@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000132, 'Miguel Dinis de Oliveira', 'miguel.dinis@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (217, 'Miguel Duarte Antunes da Silva Jorge', 'miguel.duarte@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000531, 'Miguel Filipe de Sousa Santos', 'miguelsousasantos@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000593, 'Miguel Novais Jasmins Rodrigues', 'm.rodrigues@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000309, 'Miguel Teixeira Coelho', 'mcoelho@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (100073, 'Milene Carla Russo Trindade', 'milenetrindade@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10059, 'Mónica Sofia Saraiva Saldanha', 'monica.saldanha@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000433, 'Nádia Cristina Gonçalves Pereira Gromicho', 'nadia.gromicho@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (100080, 'Natália Isabel dos Santos', 'natalia.santos@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (238, 'Natércia Maria Ferreira dos Santos', 'naterciasantos@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000626, 'Nelson Agostinho Marques Araújo', 'naraujo@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (289, 'Nelson Alexandre Araújo Valente Tondela', 'nelsontondela@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000466, 'Nelson José Pires Antunes', 'nelsonjpantunes@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (100096, 'Nelson Manuel Lopes dos Reis', 'nreis@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000195, 'Nelson Manuel Pacheco Amaral', 'nelsonamaral@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000429, 'Nelson Ricardo Brois da Silva Viana', 'nelsonv@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000434, 'Neuza Maria Eurico Cardoso', 'neuza_cardoso@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000442, 'Norberto Manuel Soares Coelho', 'norbertocoelho@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000199, 'Nuno Alexandre de Jesus Marques', 'nuno.marques@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000503, 'Nuno Alexandre dos Santos Lopes', 'nuno.a.s.lopes@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000483, 'Nuno André Mourisco Ferreira da Silva', 'nunofsilva@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (292, 'Nuno Filipe Moreira Ribeiro de Faria', 'nuno.faria@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000484, 'Nuno Filipe Ribeiro da Silva', 'fsnuno@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (253, 'Nuno José Valente Lopes Madeira', 'nmadeira@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (254, 'Nuno Manuel Guerreiro Sena', 'nuno.sena@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (100099, 'Nuno Manuel Nunes Fonseca', 'nunomnfonseca@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (219, 'Nuno Miguel de Sousa Vieira', 'nsv@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000192, 'Nuno Miguel Gameiro Dias Trindade Cardoso', 'nuno.cardoso@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000243, 'Nuno Miguel Leitão Júlio', 'nunomigueljulio@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000471, 'Nuno Miguel Mendes Vieira Branco', 'n_branco@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000587, 'Nuno Miguel Reis Marques de Sousa Gomes', 'n.s.gomes@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (415, 'Olinda Maria dos Santos Sequeira', 'olinda.sequeira@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000128, 'Oliva Maria Dourado Martins', 'oliva.martins@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000535, 'Óscar Frederico Rocha Timóteo', 'otimoteo@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000190, 'Patrícia Alves de Carvalho Lobo', 'patricia.aclobo@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000379, 'Patrícia Maria Pacheco Canelas', 'patricia.canelas@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (291, 'Patrícia Marques Ferreira da Cunha Romão', 'patricia.romao@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000210, 'Patrizia Covacci Rozzi', 'patrossi@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (279, 'Paula Alexandra Costa Leite Pinto Pereira', 'ppinto@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (15, 'Paula Alexandra da Cruz Silva Pina de Almeida', 'paula.almeida@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (240, 'Paula Alexandra Geraldes Portugal', 'pportugal@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000408, 'Paula Alexandra Lourenço dos Santos', 'paula.santos@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000271, 'Paula Bela Rosa Luís Lopes', 'plopesp@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (213, 'Paula Cristina Dias Lourenço', 'paulalourenco@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000552, 'Paula Cristina Ferreira Gomes', 'paula.gomes@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000564, 'Paula Cristina Miguel da Silva', 'paulamiguelsilva@ipt.pt', 6);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (251, 'Paulo Alexandre Gomes dos Santos', 'psantos@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000520, 'Paulo Armando Barroso da Silva Resende', 'pauloresende@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000272, 'Paulo Jorge Carrilho Pereira', 'paulo@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (358, 'Paulo Jorge Gomes Bragança', 'paulogomesbraganca@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (357, 'Paulo Jorge Natividade Rodrigues António', 'paulo.antonio@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000305, 'Paulo Jorge Norte Castanheira', 'castanheira.p@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10054, 'Paulo Manuel Ferreira da Cunha', 'paulomfcunha@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (239, 'Paulo Manuel Machado Coelho', 'pcoelho@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000606, 'Paulo Manuel Marques Lourenço', 'pmml@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000211, 'Paulo Manuel Pimenta Simão', 'paulompsimao@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000130, 'Paulo Sérgio Correia Monteiro', 'pscm@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10043, 'Pedro Alexandre da Silva Pinheiro Moitinho', '', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10073, 'Pedro Alexandre de Almeida do Vale Antunes', 'pedro.antunes@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (100100, 'Pedro Alexandre Dias Martins', 'pedromartins@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10055, 'Pedro Alexandre Pires César', '', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000494, 'Pedro Alexandre Santos de Matos', 'pmatos.techart@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000550, 'Pedro André Costa Teixeira', 'pedroteixeira@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (149, 'Pedro Augusto Nogueira Marques', 'pedromarques@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10023, 'Pedro Augusto Santana Figueiredo', 'pedrofigueiredo@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000573, 'Pedro Caetano Raposo', 'p.caetano.raposo@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (174, 'Pedro Castro Bento Moisés', 'pedro.moises@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (226, 'Pedro Daniel Frazão Correia', 'pcorreia@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (160, 'Pedro Dias dos Santos', 'pedro.santos@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (100087, 'Pedro Jerónimo Pedrosa', 'pedrojeronimo@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (252, 'Pedro Manuel Granchinho de Matos', 'granchinho@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000551, 'Pedro Manuel Nobre Freire', 'pedro-m-freire@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (250, 'Pedro Miguel Aparício Dias', 'pedrodias@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (401, 'Pedro Miguel Azeitona Gonzaga Barroso', 'pedro.barroso@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (80, 'Pedro Miguel Monteiro Casaca', 'pedro.casaca@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000260, 'Pedro Miguel Pinheiro Matos', 'pedromatos@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000574, 'Pedro Reis', 'pedroreis@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (241, 'Pierluigi Rosina', 'prosina@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000567, 'Rafael Oliveira', 'rafaeloliveira@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000581, 'Raquel Canais Rodrigues Pinheiro', 'r.pinheiro@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000268, 'Raquel de Carvalho Alves Vieira', 'raquel.v@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (62, 'Raquel Palma Tomé de Sousa Botelho', 'raquel.botelho@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (242, 'Raul Manuel Domingos Monteiro', 'raulm@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (243, 'Regina Aparecida Delfino', 're.delfino@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000196, 'Renata Duarte Candeias', 'renatacandeias@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000569, 'Renato Alexandre da Costa Machado', 'renato_machado@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (262, 'Renato Eduardo Silva Panda', 'renato.panda@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000259, 'Renato Heitor Correia Domingues', 'renato.domingues@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000487, 'Ricardo Botelho Alves', 'ricardobotelhoalves@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000590, 'Ricardo Ervideira Marques Narciso', 'ricardo-narciso@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000536, 'Ricardo Filipe Gaspar Couto', 'rfgcouto@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000270, 'Ricardo Hélder Carvalho Gonçalves', 'rgoncalves@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000261, 'Ricardo Jorge Martins Lucas', 'ricardo_lucas@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10068, 'Ricardo Jorge Santos Cardoso', 'ricardo.cardoso@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (20, 'Ricardo Jorge Viegas Covas', 'rjvc@ipt.pt', 6);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000187, 'Ricardo Manuel Nunes Lourenço', 'ricardo.lourenco@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000485, 'Ricardo Manuel Vilela Pires', 'rmvpires@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (38, 'Ricardo Nuno Taborda Campos', 'ricardo.campos@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (220, 'Ricardo Pereira Triães', 'rtriaes@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000643, 'Rita Batalha Dias Garcia Pereira', 'ritagarciapereira@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000583, 'Rita Maria Atalaia Antunes da Silva', 'ritaatalaia@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (244, 'Rita Ribeiro de Carvalho Ferreira Anastácio', 'rfanastacio@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (100091, 'Rodrigo Emanuel Branco Bertelo', 'rodrigobertelo@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000397, 'Rodrigo Esteban Teles', 'estebant.rodrigo@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (100077, 'Rodrigo José das Neves Morais', 'rodrigomorais@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000592, 'Rolando Lúcio Germano Miragaia', 'rolando.miragaia@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (245, 'Rosa Brígida Almeida Quadros Fernandes', 'rosab@ipt.pt', 6);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000548, 'Rosa Catarina Sousa Diogo', 'catarinasousadiogo@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000528, 'Rosália Isabel Duarte Rodrigues', 'rosalia.rodrigues@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000439, 'Rosana Antonio', 'rosanaantonio@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000543, 'Rúben Alexandre Lopes Martins', 'ruben-martins@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000189, 'Rúben Joaquim Pinto Loureiro', 'ruben.loureiro@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000391, 'Ruben José Pereira Feijão', 'r-feijao@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (247, 'Rui da Costa Marques Sant'' Ovaia', 'stovaia@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000584, 'Rui Jorge Maia dos Santos', 'ruimaiasantos@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (63, 'Rui Jorge Malacho Capitão', 'rui.capitao@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (294, 'Rui Manuel da Silva Alcobia', 'alcobia@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (228, 'Rui Manuel Domingos Gonçalves', 'rui.goncalves@ipt.pt', 6);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000273, 'Rui Manuel Moleirinho Fernandes', 'r.moleirinho@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000398, 'Rui Miguel da Silva Gonçalves', 'rmsgoncalves@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (229, 'Rui Miguel Sardinha Proença', 'ruiproenca@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000417, 'Rui Paulo da Silva Frade Ribeiro', 'rui.frade.ribeiro@ipt.pt', 6);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10074, 'Rui Pedro Costa Rodrigues', 'ruipcrodrigues@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000636, 'Rui Pedro Rodrigues Baptista', 'rprb@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000308, 'Rui Sainhas de Oliveira', 'rui_oliveira@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (100102, 'Samuel Caetano Augusto Martins Pereira', 'samuelp@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000390, 'Sandra Cristina Gil Vieira', 's-gomes@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000206, 'Sandra Luísa Lourenço Garrucho', 'sandragarrucho@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10053, 'Sandra Manuela Magalhães Pires', '', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000416, 'Sandra Manuela Proença Bento', 's-bento@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10033, 'Sandra Maria da Luz Casaca', 'sandra.casaca@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (182, 'Sandra Maria Gonçalves Vilas Boas Jardim', 'sandra.jardim@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (65, 'Sandra Sofia Antunes Pereira Barata', 'sandra.barata@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000630, 'Sandro Filipe Silva Gomes', 'sandrogomes@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000279, 'Sara Liliana Magalhães Barbosa Garcês', 'saragarces@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (419, 'Sara Raquel Mendes Cura', 'sara.cura@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (212, 'Sérgio Paulo Leal Nunes', 'spnunes@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (246, 'Silvério Manuel Domingues Figueiredo', 'silverio.figueiredo@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (365, 'Sílvia Catarina Henriques de Sousa', '', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000460, 'Sílvia Eduarda Nabais Martins Cerejeira', 'silviacerejeira@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000256, 'Sílvia Oliveira Sequeira', 's.o.sequeira@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (161, 'Sílvio Manuel da Rocha Brito', 'silvio.brito@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (311, 'Sílvio Manuel Valente da Silva', 'silviovsilva@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000490, 'Simão Pedro Barcelos Lopes', 'simaolopes@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (293, 'Sofia Raquel Guerra da Silva', 'sofia.rg.silva@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000262, 'Sónia Carla Fidalgo Pais', 'soniafidalgopais@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000414, 'Sónia Cristina Campos Rosa', 'soniaccrosa@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000432, 'Sónia Cristina Moreira Soares de Jesus Dias', 'sonia.dias@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000585, 'Sónia Libânia Ramos Figueiredo Rufino', 'soniaramosrufino@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (100084, 'Sónia Marisa Pedroso Gonçalves Bogas', 'sonia.goncalves@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10049, 'Soraia Alexandra Cancela da Fonseca de Vasconcelos Magalhães', 'sovasconcelos@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000269, 'Susana Adreína Conde Sancha', 'susana_sancha@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000474, 'Susana da Conceição Vieira Rodrigues', 'srodrigues@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (27, 'Susana Isabel Caetano Domingos', 'susana.domingos@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000247, 'Susana Isabel da Costa Braz', 'susana.braz@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000143, 'Susana Isabel Marçal e Silva', 'susanaimsilva@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000131, 'Tatiana Nunes Filipe', 'tatiana.filipe@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000524, 'Telma Maria de Carvalho Ferreira', 'telma.ferreira@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000396, 'Telmo Alexandre Mendes Pereira da Silva', 't.silva@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000353, 'Telmo Jorge Ramos Pereira', 'telmojrpereira@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (119, 'Teresa Leonor Ribeiro C. M. Morgado', 'tmorgado@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (22, 'Teresa Maria de Oliveira Gomes Martins', 'tmart@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000165, 'Tiago Alexandre Figueiredo Cacheiro', 'tiagocacheiro@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000401, 'Tiago André Ascensão Faria e Seixas', 'tiagoafseixas@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000253, 'Tiago André Ferreira Lopes', 'tiago-lopes@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000588, 'Tiago André Martins de Faria', 'faria.tiago@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000274, 'Tiago Emanuel da Costa Santana', 'tsantana@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000582, 'Tiago Filipe Navarro Frutuoso dos Santos Marques', 'navarro.marques@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000555, 'Tiago Manuel Henriques Carrão', 'tiagocarrao@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000519, 'Tiago Nuno Lopes Cardoso Rebelo Marinho', 'tiago.marinho@ipt.pt', 1);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (163, 'Tília dos Santos Nunes', '', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000571, 'Tobias Portela', 'tobias.portela@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000399, 'Tomás Novais Ferreirinha', 'tomasferreirinha@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (120, 'Toni dos Santos Alves', 'toni.alves@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (248, 'Valentim Maria Brunheta Nunes', 'valentim@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000530, 'Valter Alexandre Guia Sepulveda Mineiro', 'v.mineiro@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (175, 'Valter José Gonçalves Bouça', 'vbouca@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (222, 'Valter Nuno Garcez da Silva Ventura', 'valter.ventura@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (10056, 'Vanda Cristina Frazão Neves', 'vanda.neves@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000452, 'Vasco Augusto Amaro Lopes', 'vaalopes@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (39, 'Vasco Renato Marques Gestosa da Silva', 'vasco.silva@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000191, 'Vasco Ribeiro dos Santos', 'vasco.rs@ipt.pt', 4);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000614, 'Vera Simões', 'verasimoes@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (249, 'Vitor Dinis Carita de Jesus', 'vitorjesus@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (288, 'Vitor Jorge Alho da Silva Alves', 'vitorjorgealves@ipt.pt', 2);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000400, 'Vitor Jorge Cardoso freire Felicio', 'vitor.felicio@ipt.pt', 7);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000440, 'Vítor Manuel Branco Oliveira', 'vmboliveira@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000354, 'Vítor Manuel dos Santos Reis', 'vitorreis@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (297, 'Vitor Manuel Pereira Pais', 'vpais@ipt.pt', 3);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (1000578, 'Vítor Milheiro', 'vmilheiro@ipt.pt', 5);
INSERT INTO Docente (ID, Nome, Email, Password) VALUES (28, 'Zélia do Rosário de Jesus Patrocínio', 'zelia.patrocinio@ipt.pt', 3);
