USE easyscheduleipt;

INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (2, 'Plana', 'M0.T1', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (3, 'Plana', 'M2.Inf 3 (12a)', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (4, 'Plana', 'M1.Inf2.L.Redes(8a)', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (5, 'Plana', 'A.Sala 1 (48a)', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (6, 'Plana', 'A.Sala 2 (24a)', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (7, 'Plana', 'A.Auditório (42a)', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (8, 'Plana', 'A.Inf.1 (18a)', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (9, 'Plana', 'A.Inf.2 (19a)', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (10, 'Plana', 'T.At.Imp./Redação', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (11, 'Plana', 'A.At. Rádio', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (12, 'Plana', 'A.Sala Reuniões', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (14, 'Plana', 'A.Sala 3 (24a)', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (16, 'Plana', 'A.Sala Montagem', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (20, 'Plana', 'A.LDP', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (21, 'Plana', 'M1.Inf1 (14a)', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (22, 'Plana', 'M3.T3 (16a)', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (23, 'Plana', 'TN.1', 2, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (24, 'Plana', 'TN.2', 2, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (29, 'Plana', 'A.Sala 4 (LF) (16a)', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (31, 'Plana', 'A.gabinete DDP', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (40, 'Plana', 'M.SalaReuniões', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (41, 'Plana', 'A.Gab.Docente TIC', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (42, 'Plana', 'A.Sala 5 (Cl.ipt)', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (44, 'Plana', 'T.Estúdio', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (57, 'Plana', 'M2.T2 (12a)', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (60, 'Plana', 'M4.Inf 4 (13a)', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (61, 'Plana', 'Lab.Redes', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (64, 'Plana', 'A.Gab. Docente VCD', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (65, 'Plana', 'A. Gabinete CS ', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (68, 'Plana', 'TN.3', 2, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (69, 'Plana', 'TN.4', 2, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (70, 'Plana', 'TN.5', 2, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (71, 'Plana', 'TN.6', 2, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (74, 'Plana', 'T.Lab.Projeto ', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (75, 'Plana', 'T.Lab.Química', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (76, 'Plana', 'T.Lab.Materiais', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (77, 'Plana', 'T.Lab.Oficinal', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (78, 'Plana', 'T.TEF', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (79, 'Plana', 'T.Rádio', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (80, 'Plana', 'T.TV', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (81, 'Plana', 'T.Lab.Edição', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (82, 'Plana', 'T.Lab.Foto.', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (83, 'Plana', 'T.LIAI 1', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (84, 'Plana', 'T.LIAI 2', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (85, 'Plana', 'T.Lab.Mat. Comp.', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (86, 'Plana', 'T.Sala de Estudo', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (87, 'Plana', 'T.Sala Limpa MC', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (90, 'Plana', 'Auditório(tagusvaley', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (91, 'Plana', '2ºandar(tagusvalley)', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (92, 'Plana', 'FAKE', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (93, 'Plana', 'M4.T4 (8a)', 1, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (94, 'Informática', 'O101', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (95, 'Plana', 'O104', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (96, 'Plana', 'O105', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (97, 'Auditório', 'B263', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (98, 'Plana', 'Mafra1', 9, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (99, 'Plana', 'Mafra2', 9, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (100, 'Plana', 'Sala 1', 9, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (101, 'Plana', 'Sala 2', 9, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (102, 'Plana', 'Sala 3', 9, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (103, 'Plana', 'Sala 4', 9, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (104, 'Informática', 'O102', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (105, 'Plana', 'O103', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (106, 'Auditório', 'O106', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (107, 'Auditório', 'B121', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (108, 'Informática', 'B128', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (109, 'Informática', 'B135', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (110, 'Auditório', 'B253', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (111, 'Auditório', 'B254', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (112, 'Auditório', 'B255', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (113, 'Auditório', 'B256', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (114, 'Auditório', 'B257', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (115, 'Auditório', 'B258', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (116, 'Auditório', 'B259', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (117, 'Auditório', 'B260', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (118, 'Auditório', 'B261', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (119, 'Auditório', 'B262', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (120, 'Auditório', 'B264', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (121, 'Plana', 'B265', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (122, 'Plana', 'B266', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (123, 'Plana', 'B267', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (124, 'Auditório', 'B268', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (125, 'Plana', 'B269', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (126, 'Plana', 'O219', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (127, 'Auditório', 'Q102', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (128, 'Informática', 'Q201', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (129, 'Plana', 'Q203', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (130, 'Informática', 'Q204', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (131, 'Plana', 'J186', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (132, 'Plana', 'I184', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (133, 'Plana', 'I175', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (134, 'Plana', 'L150', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (136, 'Plana', 'J189', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (135, 'Plana', 'J187', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (137, 'Plana', 'B130', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (138, 'Plana', 'O128', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (260, 'Laboratório', 'I151', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (258, 'Plana', 'H191', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (259, 'Informática', 'I150', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (257, 'Laboratório', 'H188', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (256, 'Laboratório', 'H187', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (255, 'Laboratório', 'H186', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (254, 'Laboratório', 'H185', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (253, 'Laboratório', 'H184', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (252, 'Laboratório', 'H183', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (251, 'Laboratório', 'H182', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (250, 'Laboratório', 'H179', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (249, 'Plana', 'H178', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (248, 'Plana', 'H177', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (247, 'Laboratório', 'H176', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (246, 'Plana', 'H175', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (245, 'Laboratório', 'H174', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (244, 'Laboratório', 'H173', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (243, 'Plana', 'H151', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (242, 'Informática', 'H150', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (241, 'Plana', 'Lab. Mad.', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (240, 'Plana', 'G190', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (239, 'Plana', 'G183/184', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (238, 'Plana', 'G174', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (237, 'Plana', 'G173', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (236, 'Plana', 'G172', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (235, 'Plana', 'G171', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (234, 'Plana', 'G151', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (233, 'Plana', 'G150', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (261, 'Plana', 'I152', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (262, 'Laboratório', 'I153 - I191', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (263, 'Plana', 'I154', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (264, 'Laboratório', 'I173', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (265, 'Informática', 'I174', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (266, 'Informática', 'I176', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (267, 'Plana', 'I184', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (268, 'Plana', 'I185', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (269, 'Plana', 'I190', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (270, 'Laboratório', 'I192', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (271, 'Laboratório', 'J170', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (272, 'Laboratório', 'J171', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (273, 'Laboratório', 'J176', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (274, 'Plana', 'J180', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (275, 'Plana', 'J181', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (276, 'Laboratório', 'J182', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (277, 'Laboratório', 'J188', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (278, 'Plana', 'J190', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (279, 'Plana', 'H190', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (280, 'Plana', 'O218', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (281, 'Plana', 'L-TUR', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (282, 'Plana', 'Online', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (283, 'Plana', 'L151', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (284, 'Plana', 'L170', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (286, 'Plana', 'L178', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (287, 'Laboratório', 'B126', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (288, 'Laboratório', 'B132', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (289, 'Plana', 'G185', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (290, 'Laboratório', 'G176', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (291, 'Laboratório', 'G194', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (292, 'Plana', 'Lab. Mat. Pétreos', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (293, 'Laboratório', 'GCT', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (294, 'Laboratório', 'CDM', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (295, 'Plana', 'Estádio Municipal', 3, '');
INSERT INTO Sala (Cod_Sala , tipologia, Nome , Cod_Escola , __EMPTY) VALUES (296, 'Laboratório', 'ESDRM', 17, '');
